jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 3
  scmCheckoutRetryCount: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
jobs:
  - script: >
      job('seed-job') {
        scm {
          git {
            remote {
              url(System.getenv('GIT_REPO_URL'))
              credentials('github_ssh_key')
            }
            branches('**')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
        steps {
          dsl {
            external('jenkins/casc_configs/seedJob.groovy')
            removeAction('DELETE')
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "github_ssh_key"
              username: "git"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_PRIVATE_KEY}

unclassified:
  gitSCM:
    globalConfigName: "jenkins"
    globalConfigEmail: "jenkins@example.com"
    createAccountBasedOnEmail: false
    managingHooks: false
    useExistingAccountWithSameEmail: false
    accounts:
      - gitUsernamePassword:
          username: "git"
          credentialsId: "github_ssh_key"
