version: '3.8'
services:
  jenkins:
    container_name: jenkins_container
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_home/casc_configs
      - $HOME/.ssh:/var/jenkins_home/.ssh:ro
volumes:
  jenkins_home:
    name: jenkins_home_volume
